project:
  type: website
  output-dir: docs

website:
  title: "Ela Kanade's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: r_tip_of_the_day.qmd
        text: R Tip of The Day!
      - href: mini_project_4.qmd
        text: Mini Project 2


format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css

editor: visual

